# Generated by Django 4.2.23 on 2025-08-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menusubcategory",
            old_name="parent",
            new_name="category",
        ),
        migrations.AlterUniqueTogether(
            name="menusubcategory",
            unique_together={("name", "category")},
        ),
    ]
